### Figure_2_Xp_population_AUGPC

##This code has been adopted from Schandry, 2017 and modified for the current dataset parameters.
#Schandry, N. 2017. A Practical guide to visualization and statistical analysis of R. solanacearum infection data using R. Front. Plant Sci. 8 


## Reading data and formatting


#wd to set working directory. 


setwd(wd)


###Xp
Xpgrowthhigh <- read.csv("XpgrowthHigh.csv")
head(Xpgrowthhigh)
hist(Xpgrowthhigh$Population)
Xpgrowthhigh$Population2 <- scale(Xpgrowthhigh$Population, center = TRUE, scale = TRUE)
basic.lm <- lm(Population2 ~ Treatment*Day, data = Xpgrowthhigh)
summary(basic.lm)

library(lme4)
mixed.lmer <- lmer(Population2 ~ Treatment*Day + (1|Experiment), data = Xpgrowthhigh)

summary(mixed.lmer)

plot(mixed.lmer)
qqnorm(resid(mixed.lmer))
qqline(resid(mixed.lmer))

library("ggplot2")
library("cowplot")
library("afex")
library("nlme")
library("emmeans")
library("ggpubr")

m9s <- mixed(Population ~ Treatment*Day + (1|Experiment), Xpgrowthhigh, control = lmerControl(optCtrl = list(maxfun = 1e6)), 
             expand_re = TRUE)

emmeans::emm_options(lmer.df = "asymptotic")

m9s

pairs(emmeans::emmeans(m9s, c("Treatment"), by = "Day"))

stat.test.Xp <- read.csv("stats-Xphigh-significant.csv")


g <- afex_plot(m9s, x = "Treatment", panel = "Day", mapping = "color", error = "model",
               error_ci = TRUE,
               error_level = 0.95,
               error_arg = list(width = 0),
               data_plot = TRUE,
               data_geom = ggpol::geom_boxjitter,
               data_alpha = 0.5,
               data_arg = list(color = "black"),
               point_arg = list(),
               line_arg = list(),
               emmeans_arg = list(),
               dodge = 0.5,
               return = "plot",
               factor_levels = list())



g + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + facet_grid(~factor(Day, levels=c("Day 0", "Day 3", "Day 6", "Day 9", "Day 14"))) + scale_y_continuous(breaks =  c(2, 4, 6, 8), limit = c(2,8)) + theme(text = element_text(size = 17)) 

ggsave("Xp_high_population.jpg")





####making area under the growth progress curve calculating

Xpgrowthhigh <- read.csv("XpgrowthHigh_for_AUGPC.csv")
str(Xpgrowthhigh)

#If the table was properly imported, "Xnumber" columns should be either numeric, or logical (if they were empty).
#If this is the case, generation of a "subject"" column helps further analysis, which assings a unique, numeric identifier to each individual.

Xpgrowthhigh$subject <- c(1:nrow(Xpgrowthhigh))



#Install and load all required packages
library(MESS)
library(lme4)
library(lmerTest)
library(multcomp)
library(survival)
library(rms)
library(coxme)
library(stargazer)
library(survcomp)
library(tidyverse)
library(rcompanion)

#These tables need to be made long.

#````{r load tidyr, message=F}
library("tidyr")

#Now, the table of disease index recordings, needs to converted into long format for later analysis, conforming with a data structure often referred to as "tidy" (Wickham, 2008) . Long format means, that instead of having one column of each day, a new column is generated that indicates the day post infection (DPI). 

#my data imported is already in format where one column called as DPI has all disease index values.

# Next, some modifications the table structure are neccessary to make sure that all variables (columns) are in the proper format.

Xpgrowthhigh$Population <- as.numeric(Xpgrowthhigh$Population) ###Turns DI into numeric


#Now, it is time to generate the "subject" variable, unique for each subject. A unique identifier can be generated by combining information from Strain, Replicate and Batch. 


Xpgrowthhigh$subject <- interaction(Xpgrowthhigh$Treatment, Xpgrowthhigh$Replicate, Xpgrowthhigh$Experiment)



###Factorize batch information
Xpgrowthhigh$Experiment <- as.factor(Xpgrowthhigh$Experiment)



##Defining the contrasts

#A crucial step that will influence all outputs of the statistical analysis is setting the "contrasts". Contrasts specifies the "baseline" for each of the variables. "Treatment" contrasts specify that the first alphabetical level will be used as a reference for all others (see Strain below), while a "sum" constrast means that the reference value is the mean across all levels of that variable.


#{r contrasts}
####Specify what should be "appropriate" contrasts
contrasts(Xpgrowthhigh$Treatment) <- "contr.treatment"###First alphabetical strain will be the baseline
attr (Xpgrowthhigh$Treatment, "contrasts") <- contr.poly
contrasts(Xpgrowthhigh$Experiment) <- "contr.sum" ###Batches will be averaged to generate the baseline!






## Table quality check


library("broom.mixed")


str(Xpgrowthhigh)
tidy(Xpgrowthhigh) ###This can be used to assess the descriptive statistics of the data.




#Table export


write.csv(Xpgrowthhigh, file = "Xpgrowthhigh_for_AUGPC.csv")




#Session Info

sessionInfo()



###Name of the file to be read
Xpgrowthhigh <- read.table("Xpgrowthhigh_for_AUGPC.csv", sep=",", header=T)


###Redefine the variables
Xpgrowthhigh$Experiment <- as.factor(Xpgrowthhigh$Experiment)
contrasts(Xpgrowthhigh$Treatment) <- "contr.treatment"###First alphabetical strain will be the baseline!
contrasts(Xpgrowthhigh$Experiment) <- "contr.sum" ###Batches will be averaged to generate the baseline!



####Build a table of AUGPCs, per subject
auc_df <- data.frame() ###Make auc_df data frame
for (i in 1:max(as.numeric(Xpgrowthhigh$subject))) { ##Go by subject
  temp <- Xpgrowthhigh[as.numeric(Xpgrowthhigh$subject)==i,] ###Subset full table into the subject table
  temp <- droplevels(temp) ###Drop levels, so levels works properly below
  auc_df[i,1] <- i ###Subject number
  auc_df[i,2] <- levels(temp$Treatment) ###Strain
  auc_df[i,3] <- levels(temp$Experiment)###Batch
  auc_df[i,4] <- auc(temp$DPI,temp$Population)} ###AUC; i assume that trapezoid rule is fine here. 
### Additionally, auc calculation starts with the lowest x (DPI). I think this is sensible
### I assume that if one specifies "from=0", the curve is expanded by a triangle that covers the range from 
### 0 to whatever is the value at the first observation. I think the first observation should ideally be 0
### if data was recorded from the beginning..

colnames(auc_df) <- c("subject","Treatment","Experiment","AUC") ###Name columns in AUC datafarame
auc_df$Treatment <- as.factor(auc_df$Treatment) #refactor
auc_df$Experiment <- as.factor(auc_df$Experiment) #refactor
str(auc_df)


#The auc data.frame contains one area under the curve per subject and all other subject specific variables as stored in the original table.

##Analysis of differences in area under the disease progression curve

#An initial assessment of strain specific differences in AUDPC can be performed visually, for example by generating boxpots.

#{r boxplot of auc}
ggplot(auc_df) + geom_boxplot(
  aes(x=Treatment, y=AUC, color=Treatment),  #Plot boxplots of AUCs, by strains
  notch=F) +
  labs(y="AUDPC") +
  facet_wrap(~Experiment) + ###Individual plots per batch (and plant if applicable)
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  ggtitle("Figure 2\nArea Under the Growth progress Curve per strain across batches")


#Next, one can use the area under the disease progression curve, to build a linear model, or a linear mixed effects model.

#```{r load lm4 and lmerTest, message=F}
library("lme4")
library("lmerTest")

#{r analysis AUC}
summary(lm(AUC~Experiment,data=auc_df)) ###Can be used to identify batch effects. If there are none, including batch as a random factor below is not necessary (but also not necessarily wrong).

auc_lmer <- lmer(
  AUC ~ Treatment + (1|Experiment),   ### AUC modeled as a function of strain, random effects of batch 
  data=auc_df) #Linear mixed effects model.

auc_lm <- lm(AUC~Treatment+Experiment,data=auc_df) #Linear model.

AIC(auc_lm,auc_lmer) #Lower AIC, better fit, linear mixed model is slightly better for this data.
ggplot(data=auc_df, aes(y=AUC, x=Treatment)) +geom_boxplot(aes(colour=Experiment)) + ggtitle("Boxplot of AUDPC per strain by experimental batch")


#Also in this dataset, effects from Replication are observed.  

#The model can be explored using various functions, such as summary.

library("broom.mixed")
summary(auc_lmer)  ### A model summary, containing information on the model.
tidy(auc_lmer) ### A cleaner display using tidy.

###The tidy output explained:
#Term: A discription: (Intercept) overall intercept. Intercept depends on the contrasts set initially. Here treatment contrasts are used, so Intercept = First alphabetical strain (Strain1).
#StrainStrain2: Difference in the estimate (slope), between Strain2 and the (Intercept)

##Estimate: The estimated slope



#For example, we see the estimated slopes (Estimate) and standard errors, together with a t- and corresponding p-value in the output of the summary function. Note, that the above only contains information on differences between different levels and the "baseline"", which is called (Intercept).  The baseline is determined by the contrast settings that were specified earlier.

#But, it may be quite relevant to know how individual strains compare to each other (and not just how each strain compares to Strain1). This can be analyzed using a generalized linear hypothesis test, while ajusting for multiple comparisons using Tukey's method.


library("multcomp")
library("rcompanion")
library("stringr")

tidy(summary(glht(auc_lmer, linfct=mcp(Treatment="Tukey"))))


#This information can, for example, be integrated into a boxplot of the individual disease areas. Using a compact letter display, in conbination with AUDPC, combines statistical and visual information.

#{r AUC model CLD plot}
auc_cld <- cld(glht(auc_lmer, linfct=mcp(Treatment="Tukey"))) ###Save letters
auc_cld <- cbind(levels(auc_df$Treatment),auc_cld$mcletters$Letters) ###bind letters to columns
colnames(auc_cld) <- c("Treatment","Letter") ###Name columns
auc_cld <- as.data.frame(auc_cld) #Coerce to dataframe
auc_cld
###Integrate letters into auc_df##
auc_df <- left_join(auc_df,auc_cld,by="Treatment",copy=T) ###Add letter information
auc_df
###Some extra scripting to make the mean and CI plot.
summary(auc_lmer)
auc_CI <- as.data.frame(confint_tidy(auc_lmer))
auc_CI
auc_CI <- auc_CI[2:nrow(auc_CI),] ##Drop sig01, sigma
auc_CI
auc_CI$Treatment <- levels(auc_df$Treatment)
auc_CI

###Mean relative to Strain1 (except strain1 that one is absolute)

for (i in 1:nrow(auc_CI)){
  if (i==1){
    auc_CI$mean[i] <- mean(c(auc_CI$X2.5..[i],auc_CI$X97.5..[i]))
    auc_CI$upr[i] <- auc_CI$X97.5..[i]
    auc_CI$lwr[i] <- auc_CI$X2.5..[i]
  } else {
    auc_CI$mean[i] <- c(auc_CI$mean[1]+mean(c(auc_CI$X2.5..[i],auc_CI$X97.5..[i])))
    auc_CI$upr[i] <- c(auc_CI$mean[1]+auc_CI$X97.5..[i])
    auc_CI$lwr[i] <- c(auc_CI$mean[1]+auc_CI$X2.5..[i])
  }
}

auc_CI$upr

####Generate plot of meanCI of AUDCP with significance letters and raw data as jittered points
ggplot(aes(x=Treatment, y=AUC, color=Treatment),data=auc_df) +###Plot the auc_df
  geom_boxplot() + ###with jitter overplotted, symbol shape defined by batch
  geom_text(aes(x=Treatment, y=50, label=Letter),color="black", size = 6, data=auc_cld) + ###Get the letters from auc_cld 
  #and write those to position y=-3
  labs(y="AUGPC for Xp") + #Y-Axis label
  ylim(50,100)+ theme(text = element_text(size = 18)) +
  geom_jitter(color="black", size=1.2, alpha=0.9, aes(shape=Experiment))+
  ggtitle("AUGPC for Xp at high humidity") +
  labs(x= "Treatment", y= "AUGPC for Xp") +
  scale_x_discrete(labels=c('Xp', 'Xp+Pc', 'Xp+Pc+Xa', 'Xp+Xa'))

ggsave("Xp_AUGPC_high_LMM.jpg")


#The same workflow was repeated for Xp population data at low humidity as well as Xa and Pc population data collected under low and high humidity. 

#Input files are included in the folder named "input_files".
#Intermediate files are included in the folder named "intermediate_files".


